### PR TITLE
feat: add "ignorecase" enumStyle option

### PR DESCRIPTION
**Pull request by mojoaxel**
this implements #209

### CODE REVIEW

**Comment by luisfpg** [comment]
Thanks for the PR and sorry for the delay.
Would you mind adding some test cases for this?

**Comment by mojoaxel** [comment]
@luisfpg I added some tests for the enum generation.

**Comment by luisfpg** [comment]
Closes #209

**Comment by mojoaxel** [comment]
@luisfpg Why did you closes this?

**Comment by luisfpg** [comment]
Because it was merged and released in 0.23.0!

**Comment by Leonardonline** [comment]
Case `ignorecase` is not available in the [ng-openapi-gen-schema.json](https://github.com/cyclosproject/ng-openapi-gen/blob/master/ng-openapi-gen-schema.json)

**Comment by mojoaxel** [comment]
@luisfpg It looks to me like 3b47bb3cc447810c493a385a4f21632cad886887 never made it into the master branch!?
Should I open a new merge request?

**Comment by Leonardonline** [comment]
Any news about this commit?

**Comment by marcinstl** [comment]
We need this option as well. Any news?

**Comment by luisfpg** [comment]
I'm sorry for the previous mistake.
I' will be in the 0.24.0 release

**Pull request merged**
