### PR TITLE
new feature: add customizedResponseType to enable customizable respon…

### PR DESCRIPTION
**Pull request by pillsilly**
Hi 
this PR is associated with https://github.com/cyclosproject/ng-openapi-gen/issues/140

### CODE REVIEW

**Comment by luisfpg** [comment]
Hi @pillsilly, thanks for the PR.
It seems good.
But there are some failing tslint rules, which prevent build.
Try running `npm run build` and you'll see the errors. Currently:

```
ERROR: /home/luis/git/ng-openapi-gen/lib/cmd-args.ts:121:2 - file should end with a newline
ERROR: /home/luis/git/ng-openapi-gen/lib/options.ts:90:14 - " should be '
ERROR: /home/luis/git/ng-openapi-gen/lib/options.ts:90:30 - " should be '
ERROR: /home/luis/git/ng-openapi-gen/lib/options.ts:90:39 - " should be '
ERROR: /home/luis/git/ng-openapi-gen/lib/options.ts:90:48 - " should be '
ERROR: /home/luis/git/ng-openapi-gen/lib/options.ts:92:4 - Missing semicolon
ERROR: /home/luis/git/ng-openapi-gen/test/all-operations.spec.ts:17:5 - Missing semicolon
ERROR: /home/luis/git/ng-openapi-gen/test/all-operations.spec.ts:454:16 - " should be '
ERROR: /home/luis/git/ng-openapi-gen/test/cmd-args.spec.ts:6:5 - Missing semicolon
ERROR: /home/luis/git/ng-openapi-gen/test/cmd-args.spec.ts:21:9 - " should be '
ERROR: /home/luis/git/ng-openapi-gen/test/cmd-args.spec.ts:22:11 - " should be '
ERROR: /home/luis/git/ng-openapi-gen/test/cmd-args.spec.ts:22:20 - " should be '
ERROR: /home/luis/git/ng-openapi-gen/test/cmd-args.spec.ts:25:7 - Missing semicolon
ERROR: /home/luis/git/ng-openapi-gen/test/cmd-args.spec.ts:31:7 - Missing semicolon
```

Please, fix them. I'll merge afterwards.

**Comment by pillsilly** [comment]
Thanks, I missed that.
 Will provide fix soon 🤝

**Comment by pillsilly** [comment]
comment fixed, @luisfpg please check.

thank you.

**Comment by pillsilly** [comment]
@luisfpg  would you re-check this PR
thanks

**Pull request merged**
