### PR TITLE
Fix #279  Exclude API definitions with by matching the API path 

### LINKED ISSUE #279: Proposal: Exclude API definitions with a [1]more agile way in [2]earlier phase
Hi
My working project is across multiple teams and the work-flow above REST defs can be quite heavy.

Each domain might use different technology, different gen-tools for tolerancing same input yaml can be different.

e.g some of the definitions(though the swagger standard are well followed) works for team A(who use technology X) , but it might not work for team B(who use technology Y)

team B might get affected(as all defs are in the same files) by this even though team B doesn't care about definitions serves for Team A.

`ng-openapi-gen` does provide some feature that to exclude certain API that client doesn't care,

but it requires 
1. the tag has to be existed in the yaml, instead of having the control out side of the definition files.
2. even tags are all defined, `ng-openapi-gen`  still tries to read/parse the **whole**  yaml,json when processing it, and if some part of the content are not understandable by `ng-openapi-gen`  the execution goes failed.

so my rough ideas are about
1.give `ng-openapi-gen`  capability(e.g in the config file) that to exclude contents without having have to actually write tags in REST yml, every client can then freely select things to generate/not-generate with more agile way.
2.perform the exclusion logic's earlier during the process so that  the no.2 problem can be avoided.

- I actually implemented(almost) mentioned proposal locally
- I'm here to hear from community about the idea so that I can decide whether to create a PR.

@luisfpg

### PR DESCRIPTION
**Pull request by pillsilly**
A draft should be able to fix https://github.com/cyclosproject/ng-openapi-gen/issues/279
Please kindly check if it looks OK to you  @luisfpg  

If yes I will continue to add content in README.md and maybe some more refinement(like allowing user to inject their own filter logic )  

Thank you.

### CODE REVIEW

**Comment by jurgenf** [comment]
Hi @pillsilly, did you tag me by mistake? I have not participated in this issue and I am not a maintainer of this repository. If you want my feedback I can certainly look at your PR but I can't help you with getting it merged.

**Comment by pillsilly** [comment]
> Hi @pillsilly, did you tag me by mistake? I have not participated in this issue and I am not a maintainer of this repository. If you want my feedback I can certainly look at your PR but I can't help you with getting it merged.

you're right and thank you very much for reminding

**Comment by pillsilly** [comment]
@luisfpg  would you kindly help to check this PR.

**Comment by luisfpg** [comment]
Sorry, I'm having almost no time to work on this project.
Only today I managed to merge it.

**Pull request merged**
