### PR TITLE
Add HttpContext support for Angular 12+ apps.

### PR DESCRIPTION
**Pull request by Lonli-Lokli**
Fixes https://github.com/cyclosproject/ng-openapi-gen/issues/160

Please note that it requires Angular12+

### CODE REVIEW

**Comment by dasMulli** [comment]
@luisfpg is there a team / maintainer opinion on this? It's a change that we'd be interested in upstream (but can still use the templates ourselves using overrides)

**Comment by luisfpg** [comment]
It is something I'd like to include, but the current problem is the lack of time for the project.
The idea is to bump the ng-openapi-gen version to 1.0.0, requiring Angular 12 with this change.
For now, I'd say to keep using a template override.
The pace of development is slower and slower, as this project has been stable and works for our own usage at Cyclos, and having all the extra stuff is just invested time without really being useful for us.

**Comment by scurk1415** [comment]
I think you forgot to import **HttpContext** in [requestBuilder.handlebars](https://github.com/cyclosproject/ng-openapi-gen/pull/215/files#diff-48727b1ae18c87e8fcf1209c58c490496f4be3e979cb38aa054cc9ef78b19d24)

Found this issue when i copied your code for this very useful feature.

Would be really nice if this was merged

**Comment by Lonli-Lokli** [comment]
@scurk1415 Yep, you are right, thanks. We have a lot more customized templates so missed that when CtrlC+CtrlV.
I've pushed fix.

**Comment by Leonardonline** [comment]
It would be possible to add a configuration parameter to add or not this context in all services?

**Comment by willemsendennis** [comment]
> It would be possible to add a configuration parameter to add or not this context in all services?

Exactly, cause now it is a breaking change for our API(!) since it already contains a parameter named context...

**Pull request merged**
