### PR TITLE
Handlebars extension support

### PR DESCRIPTION
**Pull request by eLarocque**
Adding feature to customize Handlebars instance (ex: using custom helpers)

- Created the "HandlebarsManager" to keep the Handlebars instance and attempt to run a function declared in a `handlebars.js` file from inside the templates folder
- Added unit tests to ensure a custom helper being added can be used in the overridden template
- Added documentation in `REAME.md`

closes issue https://github.com/cyclosproject/ng-openapi-gen/issues/125

### CODE REVIEW

**Comment by luisfpg** [comment]
Thank you for the PR, great work!
By reviewing the code I could only find 1 point:
The test code for the templates is a copy of 'all-operations'.
As such, there are many definitions in the JSON descriptor, but the only assertion (which is correct) is over the description in the service itself, which comes from the tag description.
Could you update this descriptor / test, so it is simplified as much as possible to include a single operation of the tag that has description? No extra models are needed (the status code can be 201 with no schema).

**Comment by eLarocque** [comment]
The json file has been reduced. I think it's at its simplest form, let me know if there's anything I missed.

**Comment by eLarocque** [comment]
Thanks for the approval. Whenever you get a chance to trigger a release so the feature is available it would rlly help us out :) thanks!

**Comment by luisfpg** [comment]
Published in 0.14.0.

**Pull request merged**
