### PR TITLE
added "employees" example to demonstrate bug

### PR DESCRIPTION
**Pull request by tommck**
PR to demonstrate Issue https://github.com/cyclosproject/ng-openapi-gen/issues/86

### CODE REVIEW

**Comment by tommck** [comment]
Added code that's a potential bug fix, but probably in the wrong place

**Comment by luisfpg** [comment]
Actually, it was on the correct place, because otherwise the `Property` constructor would need more info on how to resolve the issue.
Thanks for the PR.

**Comment by tommck** [comment]
no problem!

**Comment by tommck** [comment]
@luisfpg are you planning on publishing a new version soon?

**Comment by luisfpg** [comment]
Yes, hopefully this week.

**Comment by tommck** [comment]
let me know if there's anything you need me to help with on that

**Comment by tommck** [comment]
@luisfpg any chance I could convince you to publish today? :)  For some reason I can't seem to install from the github url

**Comment by tommck** [comment]
Never mind.. I'm out for a couple of days, so it's no rush..

**Comment by luisfpg** [comment]
@tommck I've actually published the release.

**Pull request merged**
