### PR TITLE
Self-referencing object (array) example failing test

### PR DESCRIPTION
**Pull request by tommck**
Hope to dig through and figure out the problem shortly.

I'll also update without the focused describe too

### CODE REVIEW

**Comment by tommck** [comment]
This is related to #90 

Also, looks like we need more "hack" code in model.ts or the Property needs to be more aware of what object it's on :(

**Comment by luisfpg** [comment]
Well, taking into account that it may be deep, we should give Property more context.
For example:
```
namespace.Type:
  propertyA:
    allOf:
      - $ref: '#/components/schemas/SuperType'
      - type: object
        properties:
          deepReference:
            $ref: '#/components/schemas/namespace.Type'
```

**Comment by tommck** [comment]
oh right!.. huh.. that sounds complicated.. I'll try to take a look at it, but if you have time to do it, that would be greatly appreciated

**Comment by luisfpg** [comment]
I'll see if I can find a solution

**Comment by tommck** [comment]
I just pushed something that might fix it

**Comment by tommck** [comment]
I have no idea how to test the deep property reference stuff simply

**Comment by tommck** [comment]
@luisfpg let me know what you think about what I pushed.  Not sure if I'm missing something, since I'm new to this code / openapi stuff

**Comment by luisfpg** [comment]
@tommck I have performed a few changes:

- Pushed the container model up to the base `gen-utils.tsType`
- Removed the custom logic from `Property` itself
- Did all self-referencing tests in `self-ref` tests. I've removed the previous `employees` test because it just did the simple self-referencing test

It is merged to master. Please, test it by linking locally (see https://github.com/cyclosproject/ng-openapi-gen#developing-and-contributing). If it is OK, I'll make a new version (will actually be 0.10.0, because of #89).

**Comment by tommck** [comment]
tests passed locally.. going to try it with my actual code base in just a minute

**Comment by tommck** [comment]
Looks like it's working locally!  🥳

**Comment by tommck** [comment]
Thanks so much for being so responsive on this @luisfpg. You rock!

**Comment by luisfpg** [comment]
Great. I'll see if I can make the new version later today. Otherwise, will publish tomorrow.

**Comment by tommck** [comment]
:D
image

**Pull request merged**
